[project]
name = "osint-helper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "rich>=14.0.0",
    "sqlite-utils>=3.38",
    "textual>=3.1.1",
]
